### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Gml717** [andyc1997/KUL-Multivariate-Statistics#3]
I assume that there is not an indirect effect on behaviors (sem). Is this correct?

**Comment by andyc1997** [comment]
For Q3 and Q4, I don't know if the answers that we written are correct. It seems hard to introduce indirect effects. There are no explicit causal relationship among the constructs: violent, marriage and fraudulent. We can't set up something like: violent ~ marriage + fraudulent + religion, marriage ~ religion, fraudulent ~ religion.

**Comment by Gml717** [comment]
The correlation between violence and fraudulent is 0.699. Is that not a sufficient causal relationship among the construct? Did you check for the goodness of fit when you performed the multigroup analysis for Q3?

**Comment by andyc1997** [comment]
The correlation between constructs is correlation rather than causal relationship. It is because we are provided with prior information or theory with these constructs except for their causal relationship with religion.

**Comment by andyc1997** [comment]
Do you mean by the likelihood ratio test between configural and measurement invariance model? I checked this one.

**Comment by andyc1997** [comment]
Since both measurement invariance models are significantly different from configural model. I work on configural model for interpretation.

**Comment by Gml717** [comment]
Therefore, I should also use the configure model for the comparison of the two countries in Q5
